# -*- coding: utf-8 -*-
"""Python_Ornekler.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v2nD7JmA0Za4sJyZuK6DIQ3JInx11Zy1
"""

print("hello")
print(3+5)

ListA = [0, 1, 2, 3]
ListB = [4, 5, 6, 7]
ListA.extend(ListB)
ListA

MyTuple = (1, 2, 3, (4, 5, 6, (7, 8, 9)))
MyNewTuple =MyTuple.__add__((10, 11, 12, (13, 14, 15)))
for Value1 in MyTuple:
 if type(Value1) == int:
  print (Value1)
 else:
  for Value2 in Value1:
   if type(Value2) == int:
    print ("\t", Value2)
  else:
    for Value3 in Value2:
      print ("\t\t", Value3)

ListA = ['Turuncu', 'Sarı', 'Yeşil', 'Kahverengi']
ListB = [1, 2, 3, 4]
for Value1, Value2 in zip(ListA, ListB):
 print (Value1, '\t', Value2)

#Kullanıcıdan input alma
isim = input('İsminizi Girin : ')
print("Merhaba "+isim)

sayi = input('Sayı : ')
if(int(sayi)<0):
      print("Sayı Negatif")
elif(int(sayi)>0):
      print("Sayı Pozitif")
else:
      print("Sayı Sıfır")

for i in range(1,13):
        print(i)

for i in range(1,25):
    if i%2!=0:
        print(i)

def dikdortgenAlan(genislik, yukseklik):
    alan = float(genislik) * float(yukseklik)
    print ("Alan :",alan)
    return alan

gen = input("Genişlik :")

yuk = input("Yükseklik : ")

dikdortgenAlan(gen, yuk)

message = 'Hello There. My name is Bahadır'.split()
print(message)    # ['Hello', 'There.', 'My', 'name', 'is', 'Bahadır']
print(message[0]) # Hello

list1 = [1,2,3]
list2 = ['bir',2, True, 5.6]

list1 = ['one','two','there']
list2 = ['four','five','six']

numbers = list1 + list2 # ['one','two','there','four','five','six']

names = ['ahmet','mehmet','cenk']
for name in names:
   print(name)

print(message[0:2])
print(message[:2])
print(message[-3:-1])

list1 = ['one','two','there']
list1[1] = 'updated'
print(list1)

arabalar = ['Bmw','Mercedes','Opel','Mazda']

result = arabalar[0:3]
result = arabalar[:3]
result = arabalar[-2:]
print(result)

